MBC_userImport.class.inc
Support imports from different sources.
=> Issue28 multi sources

MBC_userImport.class.inc
Fixes #27 
Adds toolbox->getPasswordResetURL() to Mandrill template `merge_vars`: \*|PASSWORD_RESET_LINK|\*
=> Adds toolbox->getPasswordResetURL

MBC_userImport.class.inc, README.md, mbc-user-import.php
=> Issue35 att i channel source

MBC_userImport.class.inc
- `source` as "hercampus" and "herCampus"
- Point campaign sign up to:
- `'mailchimp_group_name' => 'ComebackClothes2015',`
- `'mailchimp_grouping_id' => 10641,`
=> Functional to campaign signup

MBC_userImport.class.inc, composer.json, mbc-user-import.php
=> Issue38 teenlife

MBC_userImport.class.inc
Support for different message flows for Teen Life campaign signup vs general signup
=> Support for different message flows for Teen Life

composer.json, src/MBC_UserImport_BaseSource.php, src/MBC_UserImport_Consumer.php, src/MBC_UserImport_Source_Niche.php, src/MBC_UserImport_Toolbox.php
=> Issue47 structure for sources

mbc-user-import.config.inc, src/MBC_UserImport_BaseSource.php, src/MBC_UserImport_Consumer.php, src/MBC_UserImport_Source_Niche.php, src/MBC_UserImport_Toolbox.php
=> Issue49 source niche

src/MBC_UserImport_Source_AfterSchool.php, src/MBC_UserImport_Source_Niche.php, src/MBC_UserImport_Toolbox.php
Fixes #54
Add support to track user imports from After School. 
Track:
- `SchoolShort` (`hs_name`) and `SchoolID` (`hs_id`)
- `Optin`: `SOLO` (`SINGLE_OPT_IN)` or `PAIR (`DOUBLE_OPT_IN`)
Also add data collection points in the same general points for `Niche` as well as the common `Toolbox` methods.
=> Issue54 StatHat

mbc-user-import.config.inc, src/MBC_UserImport_Source_Niche.php, src/MBC_UserImport_Toolbox.php
Fixes #57 
Add campaign signup to Birthday Mail for Niche user imports.
=> Issue57 niche campaign signup

src/MBC_UserImport_Source_Niche.php
Fixes #61 
Adjust template constants to use `v1-1-1`.
=> Updated template constants to use 1.1.1

mbc-user-import.config.inc, src/MBC_UserImport_Source_Niche.php
Fixes #63 
Adjustments to use Northstar Create User endpoint as replacement for Phoenix create user endpoint:
From:
- https://github.com/DoSomething/phoenix/blob/dev/documentation/endpoints/users.md#create-a-user
to:
- https://github.com/DoSomething/northstar/blob/dev/documentation/endpoints/users.md#create-a-user
using `MB_Toolbox` helper method.
**Related**:
- https://github.com/DoSomething/mb-toolbox/pull/62
=> Issue63 phoenix to northstar

src/MBC_UserImport_Consumer.php, tests/MBC_UserImport_ConsumerTest.php
Fixes #67 
**To Test**:
- `$ gulp test`
```
...
Time: 1.29 seconds, Memory: 6.75MB
OK (7 tests, 44 assertions)
```
=> Issue67 test coverage mbc user import consumer

src/MBC_UserImport_Consumer.php, tests/MBC_UserImport_ConsumerTest.php
Reverts DoSomething/mbc-user-import#68
=> Revert "Issue67 test coverage mbc user import consumer"

environment.php, mbc-user-import.config.inc, mbc-user-import.php, src/MBC_UserImport_Consumer.php, src/MBC_UserImport_Source_MobileappAndroid.php, src/MBC_UserImport_Source_MobileappIos.php
=> Issue72 mobile user import

src/MBC_UserImport_Source_Niche.php
Set up Niche import to point SuperStressedFace.
More info in Trello: https://trello.com/c/SM6TikBO/105-niche-new-user-import-set-up-for-superstressedface
=> Niche: New user import set up for SuperStressedFace.

src/MBC_UserImport_Source_Niche.php
=> Assign niche registration source to new Niche users.

src/MBC_UserImport_Source_Niche.php
- Changes MoCo campaign id
- Updates Mandrill templates
=> Set up integration with Game-Winning Drive campaign.

src/MBC_UserImport_Source_Niche.php
- Changes MoCo campaign id
- Updates Mandrill templates
=> Niche: change campaign to ElephantTuskForce_Sep_2016.

src/MBC_UserImport_Source_Niche.php
- Changes MoCo campaign id
- Updates Mandrill templates
=> Niche: change campaign to InnovationInspiration2016

src/MBC_UserImport_Source_Niche.php
- Updates Mandrill templates
- Turns off MobileCommons flow for current campaign
=> Niche: change campaign to Lose Your V-Card. Make SMS flow optional

composer.json, src/MBC_UserImport_Consumer.php, src/MBC_UserImport_Source_Niche.php, src/MBC_UserImport_Toolbox.php
- Fixes an issue with Validation on Northstar, see more in #87
- Improves deadLetters logging by passing exception instead of its message
- Upgrades mb-toolbox to 0.13.0
Fixes #87.
=> Niche fix northstar upsert

src/MBC_UserImport_Source_Niche.php
- Updates Mandrill templates to `v1-6-0`
cc @jamjensen
=> Niche: switch campaign to Senior Story Swap.

src/MBC_UserImport_Source_Niche.php
- Changes Phoenix campaign nid to 46
- Updates Mandrill templates to `v1-8-0`
cc @jamjensen
=> Niche: switch campaign to "Don't be a sucker".

composer.json, mbc-user-import.config.inc, src/MBC_UserImport_Source_Niche.php, src/MBC_UserImport_Toolbox.php
Refactor Mailchimp integration to API V3.
Trello: https://trello.com/c/ebQEbYzc/194-quicksilver-mailchimp-api-3-0
=> Mailchimp v3

composer.json, mbc-user-import.config.inc, src/MBC_UserImport_BaseSource.php, src/MBC_UserImport_Consumer.php, src/MBC_UserImport_Northstar_OAuthBridge.php, src/MBC_UserImport_Source_Niche.php, src/MBC_UserImport_Toolbox.php
- Refactors Niche to use Northstar library
- Improves Niche user import flow
👁 
Fixes #77, #93, #96.
Trello: https://trello.com/c/ZIQmj1sT/208-8-niche-refactor-to-northstar-gateway-library
=> Northstar client refactoring

src/MBC_UserImport_Source_Niche.php
- Changes Phoenix campaign nid to 7554
- Updates Mandrill templates to `v1-10-0`
cc @jamjensen @justkika
=> Niche: switch campaign to "Missing In History"

src/MBC_UserImport_Source_Niche.php
- Fixes broken logic on membership status determination via mobile
- Fixes existing membership determination via MailChimp error
=> Post northstar refactoring fixes

src/MBC_UserImport_Source_Niche.php
=> Fix missing mobile field in user_welcome-niche payload

src/MBC_UserImport_Source_Niche.php
Fix for #102, see https://github.com/DoSomething/mbc-user-import/issues/102#issuecomment-278154644. 
Introduced in #98.
=> Add missing event_id, signup_id fields.

src/MBC_UserImport_Source_Niche.php
- Changes Phoenix campaign nid to 7703
- Updates Mandrill templates to `v1-11-0`
cc @jamjensen
=> Switch niche campaign to "Keep 'Em Safe Behind The Wheel"

mbc-user-import.config.inc
=> Remove MailChimp-related queues

src/MBC_UserImport_Source_Niche.php
Pause for .5s to ensure we don't post too many users to customer.io
TODO: remove when rate limiter is implemented
=> Pause for .5s to ensure we don't post too many users to customer.io

src/MBC_UserImport_Source_Niche.php
- Changes Phoenix campaign nid to 3590
- Updates Mandrill templates to `v1-12-0`
=> Switch to Shower Songs / nid 3590 / templates v1-12-0

README.md, mbc-user-import.config.inc, mbc-user-import.php, src/MBC_UserImport_Source_AfterSchool.php, src/MBC_UserImport_Source_Niche.php, src/MBC_UserImport_Toolbox.php
=> Deprecate MobileCommons integration

src/MBC_UserImport_Source_Niche.php
- Changes Phoenix campaign nid to 3038
- Updates Mandrill templates to `v1-13-0`
=> Switch to Save The Mascots / nid 3038 / templates v1-13-0
